---

- name: preconfigure all nodes
  hosts: "tag_app_sap_hana_ha_demo:!tag_role_sapgui"

  pre_tasks:
    # existence of tuned package causes yum conflict in the next step, remove for idempotency
    - name: ensure tuned package is not installed
      package:
        name: tuned
        state: absent

  roles:
    - sap-preconfigure
#    - redhat_sap.sap_rhsm # replace this with rhn register step/role
    - redhat_sap.sap_hostagent

  post_tasks:
    - name: run the insights-client and upload to c.rh.c
      shell: insights-client


- name: preconfigure hana and deploy hana
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana"
  become_method: su

  roles:
    - sap-hana-preconfigure

  post_tasks:
    - name: run the insights-client and upload to c.rh.c
      shell: insights-client

- name: preconfigure netweaver and install s4 app
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_s4app"

  roles:
    - sap-netweaver-preconfigure

  post_tasks:
    - name: run the insights-client and upload to c.rh.c
      shell: insights-client

