---

- name: assign groups
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana"
  gather_facts: yes
  tasks:
    - name: find hana role
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        hdbnsutil -sr_state
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      register: find_hana_role

    - name: set mode and index
      set_fact:
        pcs_mode: "{{ (find_hana_role.stdout_lines | select('match', '^mode: (.*)$') | list)[0] | regex_replace('^mode: (.*)$', '\\1') }}"
        pcs_site_id: "{{ (find_hana_role.stdout_lines | select('match', '^site id: (.*)$') | list)[0] | default('') | regex_replace('^site id: (.*)$', '\\1') }}"

    - name: set hana role
      set_fact:
        pcs_role: "{{ 'primary' if (pcs_mode == 'primary') else 'secondary' }}"

    - name: create groups
      add_host:
        hostname: "{{ item }}"
        ansible_hostname: "{{ hostvars[item].ansible_hostname }}"
        groups: hana_{{ hostvars[item].pcs_role }}
        sap_hana_role: "{{ hostvars[item].pcs_role }}"
        sap_hana_site_id: "{{ hostvars[item].pcs_site_id }}"
      loop: "{{ ansible_play_hosts }}"


- name: check replication status (primary)
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana:&hana_primary"
  gather_facts: no
  become: yes
  become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
  become_method: su
  tasks:
    - name: ensure replication status is ACTIVE
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        python /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/python_support/systemReplicationStatus.py
        | grep '^overall system replication' | cut -d':' -f2 | awk '{$1=$1};1'
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      register: replication_status

    - name: fail when replication status is not ACTIVE
      fail:
        msg: "replication status is not ACTIVE"
      when: (replication_status.stdout != 'ACTIVE')

- name: set to maintenance mode (secondary)
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana:&hana_secondary"
  gather_facts: no
  tasks:
    - name: set to maintenance
      command: pcs property set maintenance-mode=true

    - name: stop system replication
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        sapcontrol -nr {{ sap_hana_deployment_hana_instance_number }} -function StopSystem HDB
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su


- name: unregister secondary (secondary)
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana:&hana_secondary"
  become: yes
  become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
  become_method: su

  tasks:
    - name: unregister site
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        hdbnsutil -sr_unregister --id={{ sap_hana_site_id }}
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      register: unregister_site
      when: sap_hana_site_id != ''
      failed_when:
        - unregister_site.rc > 0
        - ('this system is not a system replication site' not in unregister_site.stdout)
        - ('system must be running' not in unregister_site.stdout)
      until: unregister_site is success
      retries: 10
      delay: 5

    - name: HDB start
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        HDB start
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      register: hdb_start
      when:
        - sap_hana_site_id != ''
        - unregister_site.rc == 0
      failed_when:
        - hdb_start.rc > 0
        - ('process hdbdaemon HDB Daemon not running' not in hdb_start.stdout)


- name: upgrade (secondary)
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana:&hana_secondary"

  roles:
    - role: oatakan.rhel_upgrade
      update_reboot_kernel: yes
      become: no

  post_tasks:
    - name: set primary hostname
      set_fact:
        hana_primary_hostname: "{{ hostvars[groups['hana_primary'][0]]['ansible_hostname'] }}"

    - debug:
        msg: "{{ hana_primary_hostname }}"

    - name: re-register site after upgrade
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        hdbnsutil -sr_register --name=hdb{{ sap_hana_site_id | default(((hostvars[groups['hana_primary'][0]]['sap_hana_site_id']) | int)+1) | string }}
        --remoteHost={{ hana_primary_hostname }}
        --remoteInstance={{ sap_hana_deployment_hana_instance_number }}
        --replicationMode=syncmem
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      register: reregister_site
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      ignore_errors: yes

    - name: re-register site after upgrade online mode
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        hdbnsutil -sr_register --name=hdb{{ sap_hana_site_id | default(((hostvars[groups['hana_primary'][0]]['sap_hana_site_id']) | int)+1) | string }}
        --remoteHost={{ hana_primary_hostname }}
        --remoteInstance={{ sap_hana_deployment_hana_instance_number }}
        --replicationMode=syncmem
        --online
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      when: ('system must be shut down' in reregister_site.stdout)
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      ignore_errors: yes

    - name: reboot system
      reboot:

    - name: HDB start
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        HDB start
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      ignore_errors: yes


- name: wait for system replication (primary)
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana:&hana_primary"

  tasks:
    - name: wait until system replication status is active
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        python /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/python_support/systemReplicationStatus.py
        | grep '^overall system replication' | cut -d':' -f2 | awk '{$1=$1};1'
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/python_support
      register: wait_sys_replication
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      until: wait_sys_replication.stdout == 'ACTIVE'
      retries: 300
      delay: 10
      failed_when: false


#- name: Suspend DB
#  hosts: "tag_app_sap_hana_ha_demo:&tag_role_s4app"
#  become: yes
#  become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
#  become_method: su
#  tasks:
#    - name: DB suspension
#      file:
#        path: /usr/sap/RHE/SYS/global/hdb_quiesce.dat
#        state: touch
#
#    - name: wait for disconnect
#      wait_for:
#        file: /usr/sap/RHE/D00/work/dev_w<#>   # look for the latest file
#        line: "disconnected from HDB"


- name: fail over (secondary)
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana:&hana_secondary"
  pre_tasks:
    - name: set new primary hana server ip
      add_host:
        name: hana_primary
        ip_address: "{{ ansible_ip_addresses[0] | default(ec2_private_ip_address) | default(private_ip) | default(ansible_host) | default(ansible_ssh_host) }}"

    - debug:
        var: hostvars['hana_primary']['ip_address']
  tasks:
    - name: set maintenance off
      command: pcs property set maintenance-mode=false

    - pause:
        seconds: 30

    - name: fail over to secondary
      command: >
        crm_resource --move
        --resource SAPHana_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }}-clone -H {{ ansible_fqdn }}

    - name: wait for status to be primary
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        hdbnsutil -sr_state | grep 'operation mode{{":"}} primary'
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      register: wait_for_status
      until: wait_for_status is success
      retries: 30
      delay: 30
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su

#    - name: wait for clone set
#      shell: pcs status | grep "FAILED Master {{ ansible_fqdn }}"
#      register: wait_for_clone_set
#      until: wait_for_clone_set is success
#      ignore_errors: yes
#      retries: 30
#      delay: 3

    - pause:
        seconds: 60

    - name: pcs restore
      command: >
        pcs resource clear
        SAPHana_{{ sap_hana_deployment_hana_sid }}_{{ sap_hana_deployment_hana_instance_number }}-clone

    - name: wait until system replication status is active
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        python /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/python_support/systemReplicationStatus.py
        | grep '^overall system replication' | cut -d':' -f2 | awk '{$1=$1};1'
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/python_support
      register: wait_sys_replication
      until: wait_sys_replication.stdout == 'ACTIVE'
      retries: 300
      delay: 10
      failed_when: false
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su

- name: move the vip on s4app
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_s4app"
  vars:
    # this a temporary measure before implementing real vip
    sap_hana_vip: "{{ hostvars['hana_primary']['ip_address'] }}"
  roles:
    - s4-hosts

- name: upgrade (primary)
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana:&hana_primary"
  pre_tasks:
    - name: set to maintenance
      command: pcs property set maintenance-mode=true

    - name: stop system replication
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        sapcontrol -nr {{ sap_hana_deployment_hana_instance_number }} -function StopSystem HDB
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su

    - name: unregister site
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        hdbnsutil -sr_unregister --id={{ sap_hana_site_id }}
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      register: unregister_site
      when: sap_hana_site_id != ''
      failed_when:
        - unregister_site.rc > 0
        - ('this system is not a system replication site' not in unregister_site.stdout)
        - ('system must be running' not in unregister_site.stdout)
      until: unregister_site is success
      retries: 10
      delay: 5

    - name: HDB start
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        HDB start
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      register: hdb_start
      when:
        - sap_hana_site_id != ''
        - unregister_site.rc == 0
      failed_when:
        - hdb_start.rc > 0
        - ('process hdbdaemon HDB Daemon not running' not in hdb_start.stdout)

  roles:
    - role: oatakan.rhel_upgrade
      update_reboot_kernel: yes
      become: no

  post_tasks:
    - name: set primary hostname
      set_fact:
        hana_primary_hostname: "{{ hostvars[groups['hana_secondary'][0]]['ansible_hostname'] }}"

    - debug:
        msg: "{{ hana_primary_hostname }}"

    - name: re-register site after upgrade
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        hdbnsutil -sr_register --name=hdb{{ sap_hana_site_id | default(((hostvars[groups['hana_primary'][0]]['sap_hana_site_id']) | int)+1) | string }}
        --remoteHost={{ hana_primary_hostname }}
        --remoteInstance={{ sap_hana_deployment_hana_instance_number }}
        --replicationMode=syncmem
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      register: reregister_site
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      ignore_errors: yes

    - name: re-register site after upgrade online
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        hdbnsutil -sr_register --name=hdb{{ sap_hana_site_id | default(((hostvars[groups['hana_primary'][0]]['sap_hana_site_id']) | int)+1) | string }}
        --remoteHost={{ hana_primary_hostname }}
        --remoteInstance={{ sap_hana_deployment_hana_instance_number }}
        --replicationMode=syncmem
        --online
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      when: ('system must be shut down' in reregister_site.stdout)
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su

    - name: reboot system
      reboot:

    - name: HDB start
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        HDB start
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su

- name: wait for system replication (secondary)
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana:&hana_secondary"
  become: yes
  become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
  become_method: su

  tasks:
    - name: wait until system replication status is active
      shell: >
        source /usr/sap/{{ sap_hana_deployment_hana_sid }}/home/.sapenv.sh &&
        python /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/python_support/systemReplicationStatus.py
        | grep '^overall system replication' | cut -d':' -f2 | awk '{$1=$1};1'
      args:
        chdir: /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/python_support
      register: wait_sys_replication
      until: wait_sys_replication.stdout == 'ACTIVE'
      retries: 300
      delay: 10
      failed_when: false

- name: rerun the insights client
  hosts: "tag_app_sap_hana_ha_demo:&tag_role_hana"
  tasks:
    - name: run the insights-client and upload to c.rh.c
      shell: insights-client 
